name: beuty_support
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.8.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI & Device
  device_preview: ^1.3.1
  flutter_screenutil: ^5.9.3
  cupertino_icons: ^1.0.8

  # Firebase (أحدث نسخ مستقرة متوافقة)
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1
  cloud_firestore: ^6.0.0
  firebase_storage: ^13.0.0

  # Image Picker (أحدث نسخ مستقرة)
  image_picker: ^1.1.2
  image_picker_for_web: ^3.0.6
  image_picker_android: ^0.8.12+25

  # Localization
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  shared_preferences: ^2.5.3

  # State Managment
  provider: ^6.1.5

  dropdown_button2:

dev_dependencies:
  intl_utils: ^2.8.11
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/

  fonts:
    - family: Delius
      fonts:
        - asset: assets/fonts/Delius-Regular.ttf
    - family: Zain
      fonts:
        - asset: assets/fonts/Zain-Bold.ttf
flutter_intl:
  enabled: true
