// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQ89qNvXyISMpP8EBEw_R0MmKVwR7dZfQ',
    appId: '1:904006621832:android:3bd672bdbf724f05e59d3d',
    messagingSenderId: '904006621832',
    projectId: 'beautysupport-7df1b',
    storageBucket: 'beautysupport-7df1b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSH1hFPqiPCM5kTYueKtQSDwXHYBCzBVA',
    appId: '1:904006621832:ios:addb7decff33df9ae59d3d',
    messagingSenderId: '904006621832',
    projectId: 'beautysupport-7df1b',
    storageBucket: 'beautysupport-7df1b.firebasestorage.app',
    iosBundleId: 'com.example.beutySupport',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRmDC0UZ-qJwXq_KQkX5F-Dk9g2Psfr_k',
    appId: '1:904006621832:web:7dff352dc63a0ef8e59d3d',
    messagingSenderId: '904006621832',
    projectId: 'beautysupport-7df1b',
    authDomain: 'beautysupport-7df1b.firebaseapp.com',
    storageBucket: 'beautysupport-7df1b.firebasestorage.app',
    measurementId: 'G-TDFRP7X1QL',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSH1hFPqiPCM5kTYueKtQSDwXHYBCzBVA',
    appId: '1:904006621832:ios:addb7decff33df9ae59d3d',
    messagingSenderId: '904006621832',
    projectId: 'beautysupport-7df1b',
    storageBucket: 'beautysupport-7df1b.firebasestorage.app',
    iosBundleId: 'com.example.beutySupport',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRmDC0UZ-qJwXq_KQkX5F-Dk9g2Psfr_k',
    appId: '1:904006621832:web:700469cd9b542c4be59d3d',
    messagingSenderId: '904006621832',
    projectId: 'beautysupport-7df1b',
    authDomain: 'beautysupport-7df1b.firebaseapp.com',
    storageBucket: 'beautysupport-7df1b.firebasestorage.app',
    measurementId: 'G-70C5WZR7JE',
  );
}
